name:                HRPayroll
version:             0.1.0.0
github:              "githubuser/HRPayroll"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HRPayroll#readme>

dependencies:
- base >= 4.7 && < 5
- hourglass >= 0.2.11
- mtl
- containers 
- extra >= 1.6.8
- test-fixture >= 0.5.1.0
- hspec >= 2.4.8
- template-haskell >= 2.11.1.0
- QuickCheck >= 2.10.1
- time >= 1.8.0.2
- extra >= 1.6.8

library:
  source-dirs: src

executables:
  HRPayroll-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HRPayroll

tests:
  HRPayroll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HRPayroll
